<?php
/**
 * @var ATCP\MageAcademy\Block\ImageListBlock $block
 */
?>
<style>
    img {
        max-width: 100%;
        height: auto
    }

    div {
        text-align: center;
    }

    table, th, td {
        border: 1px solid white;
        border-collapse: collapse;
    }
</style>

<h3>Product list</h3>

<table>
    <tr>
        <th>Product ID</th>
        <th>Product URL</th>
        <th>Product Image</th>
    </tr>

    <?php foreach($block->getImageList() as $key): ?>
    <tr>
        <td><?= $key['id']; ?></td>
        <td><?= $key['imageUrl']; ?></td>
        <td><img src="<?= $key['imageUrl']; ?>" alt = "<?= $key['name']; ?>"></td>
    </tr>
    <?php endforeach; ?>
</table>


