<style>
    h1 {
        text-align: center
    }

    table, th, td {
        border: 1px solid black;
    }

    table {
        alig
    }
</style>
<h1>World clocks</h1>
<table>
    <tr>
        <th>City</th>
        <th>Time</th>
    </tr>
    <tr>
        <td>Warsaw</td>
        <td>
            <?php

            /**
             * @var ATCP\MageAcademy\Block\MySpeakingBlock $block
             */

            echo $block->saySomething('Europe/Warsaw');
            ?>
        </td>
    </tr>
    <tr>
        <td>New York</td>
        <td>
            <?php
            echo $block->saySomething('America/New_York');
            ?>
        </td>
    </tr>
    <tr>
        <td>Sydney</td>
        <td>
            <?php
            echo $block->saySomething('Australia/Sydney');
            ?>
        </td>
    </tr>
    <tr>
        <td>Tokyo</td>
        <td>
            <?php
            echo $block->saySomething('Asia/Tokyo');
            ?>
        </td>
    </tr>
</table>

